// JavaScript has dynamic objects
// Which means that without defining classes first
// We can create new type of objects, and that type
// will be dynamically generated by javascript's engine

let John = 
{
	firstname : "John",
	lastname  : "Doe",
	getFullName()
	{
		return firstname + ' ' + lastname;
	}
};

// but, if we want to create the same type of object,
// without defining a class, we have to repeat the code
let Sarah = 
{
	firstname : "Sarah",
	lastname  : "Doe",
	getFullname()
	{
		return firstname + ' ' + lastname;
	}
};

// instead of repeating the code, we can have factory function
// which will retorn this 'type' of objects
function createPerson(firstname, lastname)
{
	return {
		firstname : firstname,
		lastname : lastname,
		getFullname() {
			return firstname + ' ' + lastname;
		}
	}
}
